### ISSUE TITLE
404 Errors & CDN Integration

### ISSUE THREAD

**Issue by klummy** [FreeCodeCampLagos/FreeCodeCampLagos.github.io#20]
Hello,

There are four (4) 404 errors in the console. The favicon.ico error may be ignored but the others could be fixed.

Also, why not let's server vendor code - Bootstrap, Jquery - via CDN?

**Comment by ekpo-d** [comment]
hi @klummy, thanks for raising these issues, i guess we didnt include CDN because we are still testing and need the raw files/file version. The CDNs will be included before pushed to master.

I've been testing, but havent come across the 404 errors save for the favicon.  Although, there was an issue with link refrences but thats been fixed

Thanks again! :+1:
